services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
  postgres_test:
    image: postgres:16-alpine3.19
    container_name: postgres_test_container
    environment:
      POSTGRES_DB: top_education
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"